### PR TITLE
Issue-84: The `custom_date_range` aggregation does not allow for removing the start date

### LINKED ISSUE #84: The `custom_date_range` aggregation does not allow for removing the start date
### Description of the bug

The `custom_date_range` is an array of values, so if you remove either the start or end date, the array has only one element, and since it's an array, there's no way of knowing whether the remaining date is the start or end date.

Ideally, after removing the start date, the data would look like `[ '', '2025-01-01' ]`, which would make it obvious that the start date was removed. But the `array_filter() in Custom_Date_Range->extract_query_values()` (https://github.com/alleyinteractive/elasticsearch-extensions/blob/main/lib/aggregations/class-custom-date-range.php#L63) filters out empty array elements, so the data looks like `[ '2025-01-01' ]`, making it impossible to tell if it was the start or end date that was removed.

The bug results in the end date replacing the start date, and the end date being empty.

### Steps To Reproduce

1. Utilize `elasticsearch-extensions` to build a search query with `custom_date_aggregation`
2. Clear the start date
3. Notice that the end date takes the place of the start date and the end date becomes empty

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by nikkifurls**
### Summary

Fixes #84

This pull request addresses a bug in the `custom_date_range` aggregation where removing the start date causes the end date to replace the start date, and the end date becomes empty. The issue stems from the `array_filter()` in `Custom_Date_Range->extract_query_values()` filtering out empty array elements, making it unclear whether the start or end date was removed.

### Changes

- Updates the custom date range aggregation to use separate query variables for the date range (`custom_date_range_start` and `custom_date_range_end`), instead of an array of values (`custom_date_range`)

### Test Plan

1. Build a search query using `elasticsearch-extensions` with `custom_date_aggregation`.
2. Clear the start date and verify that the data structure reflects `[ '', '2025-01-01' ]` instead of `[ '2025-01-01' ]`.
3. Run the test suite to confirm no regressions and the new test cases pass as expected.

### Additional Notes

This fix ensures that the `custom_date_range` aggregation properly handles empty start or end dates, maintaining clarity in the data structure.

### CODE REVIEW

File: lib/aggregations/class-custom-date-range.php [hunk 1]
```diff
@@ -18,6 +18,20 @@
  */
 class Custom_Date_Range extends Aggregation {
 
+	/**
+	 * The query var for the start date.
+	 *
+	 * @var string
+	 */
+	protected string $query_var_start = 'custom_date_range_start';
```
Comment (mboynes) [inline lib/aggregations/class-custom-date-range.php:26]: nitpicky comment, but these are long query var names and it's generally a good idea to keep query vars short. browsers have url length limits which vary by browser (cool), and while they're usually pretty reasonable (~2k), you'd be surprised how quickly a search form can reach that limit. My suggestion would be to make these `date_gte` and `date_lte`.

**Review by mboynes — APPROVED** [review]

File: lib/aggregations/class-custom-date-range.php (hunk 1 above)
Comment (nikkifurls) [reply lib/aggregations/class-custom-date-range.php]: Thank you for that feedback, and that's a very good point! Naming stuff is hard 😝

Updated! 🙌
